<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-07T09:31:43 GMT-05:00" name="Suite" finished-at="2023-02-07T09:32:27 GMT-05:00" duration-ms="44173">
    <groups>
      <group name="LoginCreds">
        <method signature="LoginCredsTest.invaidPassword()[pri:0, instance:tests.LoginCredsTest@7bbc8656]" name="invaidPassword" class="tests.LoginCredsTest"/>
        <method signature="LoginCredsTest.invalidEmail()[pri:0, instance:tests.LoginCredsTest@7bbc8656]" name="invalidEmail" class="tests.LoginCredsTest"/>
      </group> <!-- LoginCreds -->
    </groups>
    <test started-at="2023-02-07T09:31:43 GMT-05:00" name="Grouping" finished-at="2023-02-07T09:32:27 GMT-05:00" duration-ms="44173">
      <class name="tests.LoginCredsTest">
        <test-method is-config="true" signature="launch()[pri:0, instance:tests.LoginCredsTest@7bbc8656]" started-at="2023-02-07T09:31:43 GMT-05:00" name="launch" finished-at="2023-02-07T09:31:52 GMT-05:00" duration-ms="8223" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method signature="invaidPassword()[pri:0, instance:tests.LoginCredsTest@7bbc8656]" started-at="2023-02-07T09:31:52 GMT-05:00" name="invaidPassword" finished-at="2023-02-07T09:32:08 GMT-05:00" duration-ms="16547" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invaidPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginCredsTest@7bbc8656]" started-at="2023-02-07T09:32:08 GMT-05:00" name="tearDown" finished-at="2023-02-07T09:32:11 GMT-05:00" duration-ms="3258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launch()[pri:0, instance:tests.LoginCredsTest@7bbc8656]" started-at="2023-02-07T09:32:11 GMT-05:00" name="launch" finished-at="2023-02-07T09:32:17 GMT-05:00" duration-ms="5920" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method retried="true" signature="invalidEmail()[pri:0, instance:tests.LoginCredsTest@7bbc8656]" started-at="2023-02-07T09:32:17 GMT-05:00" name="invalidEmail" finished-at="2023-02-07T09:32:19 GMT-05:00" duration-ms="1517" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Usr does not exist.] but found [User does not exist.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Usr does not exist.] but found [User does not exist.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at tests.LoginCredsTest.invalidEmail(LoginCredsTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidEmail -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginCredsTest@7bbc8656]" started-at="2023-02-07T09:32:19 GMT-05:00" name="tearDown" finished-at="2023-02-07T09:32:19 GMT-05:00" duration-ms="476" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launch()[pri:0, instance:tests.LoginCredsTest@7bbc8656]" started-at="2023-02-07T09:32:19 GMT-05:00" name="launch" finished-at="2023-02-07T09:32:25 GMT-05:00" duration-ms="5307" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method signature="invalidEmail()[pri:0, instance:tests.LoginCredsTest@7bbc8656]" started-at="2023-02-07T09:32:25 GMT-05:00" name="invalidEmail" finished-at="2023-02-07T09:32:27 GMT-05:00" duration-ms="2080" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Usr does not exist.] but found [User does not exist.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Usr does not exist.] but found [User does not exist.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at tests.LoginCredsTest.invalidEmail(LoginCredsTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidEmail -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginCredsTest@7bbc8656]" started-at="2023-02-07T09:32:27 GMT-05:00" name="tearDown" finished-at="2023-02-07T09:32:27 GMT-05:00" duration-ms="421" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.LoginCredsTest -->
    </test> <!-- Grouping -->
  </suite> <!-- Suite -->
</testng-results>
